### ISSUE TITLE
City / State based export broken

### ISSUE THREAD

**Issue by DanHues** [louis-e/arnis#37]
Hey, I attempted to run the city based export instead of the box based selection to have a larger region of Gainesville, Florida. The render took 121 minutes but exported a pretty empty region, and in specific parts its completely empty / cut off

PC Specs
CPU: Ryzen 7 5800X
Ram: 96GB DDR4 1599mhz
GPU: RTX 3090

![javaw_8a4P3ci1c3](https://github.com/user-attachments/assets/dff7d8cc-56c1-4415-add0-8ba2e706d05f)
![cmd_4Kzl1B1hi8](https://github.com/user-attachments/assets/01f7f890-088e-4319-bc22-c29679df0b17)

**Comment by amir16yp** [comment]
I will try to reproduce this.
try to run your command again with --debug, then tell me what the output of arnis-debug-map.png is. it should be generated after processing elements and before the generating pixels.
also does this not occur if you do the same area with the bounding box?

**Comment by louis-e** [comment]
Hi there!
Well, this is a known issue we had for a very long time with the city / state / country input. That's why I decided to set the bbox input as the standard option and to not longer actively support the other input arguments. I left it in just in case, but I can only recommend trying it with bbox - the README contains a guide for that.
I will also push a huge refactoring tomorrow which improves the visuals and generation time massively, so stay tuned! :)

**Comment by DanHues** [comment]
> Hi there! Well, this is a known issue we had for a very long time with the city / state / country input. That's why I decided to set the bbox input as the standard option and to not longer actively support the other input arguments. I left it in just in case, but I can only recommend trying it with bbox - the README contains a guide for that. I will also push a huge refactoring tomorrow which improves the visuals and generation time massively, so stay tuned! :)

Thanks for the quick response! I was able to get a decently sized export of the downtown Gainesville area. But, I'm working on creating a series for shortform content platforms based around the idea of building my hometown in Minecraft. without that command is there a way to do selections that are bigger than the Openstreetmaps 50k limit? 

Also, wanted to say this project is amazing! Its super seamless, im excited to see the future development of this for sure! 
The box based export came out mostly solid

![javaw_CDh68POCn3](https://github.com/user-attachments/assets/babd3d2f-218e-44e6-8d79-6ed84e956ec9)

but, on my export some of the buildings are missing 

![Untitled](https://github.com/user-attachments/assets/0639df1a-d929-4af7-8ee2-9f7053b12940)
![Untitled2](https://github.com/user-attachments/assets/cdc92ec0-bebb-4322-9c32-b6bdf98e20e2)

Thanks again, seriously amazing work!

**Comment by DanHues** [comment]
Heres a debug png for a box selection of downtown Gainesville Florida
![arnis-debug-map](https://github.com/user-attachments/assets/4df5ef09-ab48-48b7-9c79-f853ad62545b)

The entire city is going to take a few hours so I will respond with that later lmao

**Comment by amir16yp** [comment]
> > Hi there! Well, this is a known issue we had for a very long time with the city / state / country input. That's why I decided to set the bbox input as the standard option and to not longer actively support the other input arguments. I left it in just in case, but I can only recommend trying it with bbox - the README contains a guide for that. I will also push a huge refactoring tomorrow which improves the visuals and generation time massively, so stay tuned! :)
> 
> Thanks for the quick response! I was able to get a decently sized export of the downtown Gainesville area. But, I'm working on creating a series for shortform content platforms based around the idea of building my hometown in Minecraft. without that command is there a way to do selections that are bigger than the Openstreetmaps 50k limit?
> 
> Also, wanted to say this project is amazing! Its super seamless, im excited to see the future development of this for sure! The box based export came out mostly solid
> 
> ![javaw_CDh68POCn3](https://private-user-images.githubusercontent.com/43981251/358057404-babd3d2f-218e-44e6-8d79-6ed84e956ec9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2ODUwNTMsIm5iZiI6MTcyMzY4NDc1MywicGF0aCI6Ii80Mzk4MTI1MS8zNTgwNTc0MDQtYmFiZDNkMmYtMjE4ZS00NGU2LThkNzktNmVkODRlOTU2ZWM5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDAxMTkxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1NGVhZDc2NjlmMTVjZjJiNjMxN2FiMWQ3MThhOTBmOTliYjdkZDVlODcyNjI4ZjUwNTg1YTYyMTMyNDgwZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xv7iweH0kCsFMTHk0ZlAMtdP6eZUMmBgna_AHN9MmWs)
> 
> but, on my export some of the buildings are missing
> 
> ![Untitled](https://private-user-images.githubusercontent.com/43981251/358057458-0639df1a-d929-4af7-8ee2-9f7053b12940.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2ODUwNTMsIm5iZiI6MTcyMzY4NDc1MywicGF0aCI6Ii80Mzk4MTI1MS8zNTgwNTc0NTgtMDYzOWRmMWEtZDkyOS00YWY3LThlZTItOWY3MDUzYjEyOTQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDAxMTkxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhMThjYjk5YjVhZjdhNWUwYTNiNDRkYjg2ZmJkNDRlZDhiOGZmY2U2Y2IzMzRhYWVlZDYwMjYzN2VjYjMyM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pZF7k14Zr5ZG-FoF3Cce7b2XDEzjyaeFSeoZCCXkjNw) ![Untitled2](https://private-user-images.githubusercontent.com/43981251/358057830-cdc92ec0-bebb-4322-9c32-b6bdf98e20e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2ODUwNTMsIm5iZiI6MTcyMzY4NDc1MywicGF0aCI6Ii80Mzk4MTI1MS8zNTgwNTc4MzAtY2RjOTJlYzAtYmViYi00MzIyLTljMzItYjZiZGY5OGUyMGUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDAxMTkxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkMTBmNWJjZWUzNjg1ODJkODA5YTkyOThjZWY1ZjczYWU3ODgzMjFlNTM5NDBlNzY2MmZiY2MxZjBlMGY2NWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oZU3TtTWtQQC1tpXziazFDjl7prHesPu5zmaJpT2O34)
> 
> Thanks again, seriously amazing work!

i just a noticed pattern, almost all the buildings that are missing here are not exactly rectangles nor round, and all but one have a hole in them. might have something to do with it

**Comment by DanHues** [comment]
Interesting, the debug png for this iteration of the city command generated this. 
![arnis-debug-map](https://github.com/user-attachments/assets/d36e1d2b-0ff7-4055-b4be-e304109c42ce)

**Comment by amir16yp** [comment]
i recommend using the automap feature with the journeymap mod. then you could view the map and teleport anywhere. you might have spawned in an empty space, and the distance to the actual city is quite large, so you might at first think the map didnt generate properly

**Comment by DanHues** [comment]
> i recommend using the automap feature with the journeymap mod. then you could view the map and teleport anywhere. you might have spawned in an empty space, and the distance to the actual city is quite large, so you might at first think the map didnt generate properly

Hey so after teleporting around on singleplayer it was looking completely fine then comparing it to my server with the world imported, it looks like the data got corrupted when i imported the world into my build server.

**Comment by DanHues** [comment]
> i recommend using the automap feature with the journeymap mod. then you could view the map and teleport anywhere. you might have spawned in an empty space, and the distance to the actual city is quite large, so you might at first think the map didnt generate properly

Alright i confirmed it, it was my Multi world plugin, after reexporting the world with the state command 
![image](https://github.com/user-attachments/assets/e88afef9-7798-4a1f-a897-92ee3a98c501)
hey look i can see my house from here!

Also on a note about the missing buildings, it looks like missing buildings occur when there are alot of layers on top of a specific zone. 

for example, the library on UF's campus
![image](https://github.com/user-attachments/assets/0d87986b-58a1-440a-908a-ac188a16cdd1)
in game its missing the entire building

on open street maps
![image](https://github.com/user-attachments/assets/abe2a761-e2e7-40bb-91fc-04148df30131)


I noticed this issue around specific roads aswell. 
![image](https://github.com/user-attachments/assets/596d6455-2703-4610-bd79-fe906306079a)

![image](https://github.com/user-attachments/assets/5e26b3fc-b9b6-4265-9e47-70ed9bf498bd)

**Comment by DanHues** [comment]
btw, do you have a discord for this project? I'd love to join and follow this along its development 

Also, since its in a similar vein i think yall might be interested in this
https://www.patreon.com/AtmosphericBeatsMC/
This guy makes custom worlds using OpenStreetmaps data and geotiff to make city maps with heightmaps but the worlds are exported into a .world file for worldpainter and then exported using worldpainter as a baseplate.

**Comment by louis-e** [comment]
I guess I'm a bit late for the conversation here, but it's nice to see everyone helping out! :)

Just a few notes from my side:
> is there a way to do selections that are bigger than the Openstreetmaps 50k limit?

I don't think so, I guess this depends on the used OSM API server. Maybe there is one without such an limit (https://wiki.openstreetmap.org/wiki/Overpass_API#Public_Overpass_API_instances). Maybe you can look into hosting your own modified API server, but that sounds a bit time consuming to set up ;) This is just my guess though, I'd have to do some more research on this. https://github.com/drolbr/Overpass-API

> but, on my export some of the buildings are missing

Can you check if this problem still occurs with the last refactoring update I just merged?

> i just a noticed pattern, almost all the buildings that are missing here are not exactly rectangles nor round, and all but one have a hole in them. might have something to do with it

Initial thought: This might be the floodfill algorithm having problems with finding an inner point in the object. See comment above; I updated the floodfill algorithm too in the recent refactoring update, so this might be fixed. Let me know if this is still an issue!

> Also on a note about the missing buildings, it looks like missing buildings occur when there are alot of layers on top of a specific zone.

This might also have been true, but same as above; the processing pipeline is now way more precise, efficient and faster :)

**Comment by DanHues** [comment]
> Can you check if this problem still occurs with the last refactoring update I just merged?

For sure! On the latest build the buildings are still missing 
![javaw_BaDK2ZsGEi](https://github.com/user-attachments/assets/ef4e6a78-5efd-4934-8cdb-af03ad6379fd)

**Comment by louis-e** [comment]
After reproducing the issue and inspecting the arnis-debug-processed_data.json, this is what I have observed so far:

Healthy element:
![image](https://github.com/user-attachments/assets/fa0cdf45-b5c9-4e5c-bf2d-204da8bab7ac)

Corrupted element:
![image](https://github.com/user-attachments/assets/8950a4ce-4bd6-4d0f-bf99-3e94f51974e9)

The missing buildings (corrupted elements) contain a reference to the node coordinates rather than actually containing the coordinates and are classified as a relation rather than a way data type. This is the way how we receive the data from the API, so the processing code just skips them. Will look into this!

**Comment by louis-e** [comment]
I investigated this further and wrote some dummy code, I'm going to implement the logic when I have time to extensively test it! 
![image](https://github.com/user-attachments/assets/f75c6481-4f2b-4f1f-8715-1519ab6b7c1d)

**Comment by louis-e** [comment]
Please check if this issue is still occuring in the new release (Arnis v2.0.0)! https://github.com/louis-e/arnis/releases/tag/v2.0.0
